# Generated by Django 5.2.8 on 2025-12-02 14:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Morning Delivery, Afternoon Delivery', max_length=100)),
                ('cut_off_time', models.TimeField(help_text='Order cut-off time for this slot')),
                ('delivery_start_time', models.TimeField(help_text='When delivery starts for this slot')),
                ('delivery_end_time', models.TimeField(help_text='When delivery ends for this slot')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_time_slots',
                'ordering': ['cut_off_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, help_text='Base delivery fee for this zone', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('max_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('min_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('max_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_manual_pricing', models.BooleanField(default=False, help_text='If True, use manual pricing instead of distance calculation')),
                ('manual_delivery_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Manual delivery fee (overrides calculation)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='markets.market')),
            ],
            options={
                'db_table': 'delivery_zones',
                'ordering': ['market', 'name'],
                'unique_together': {('market', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='e.g., Home, Work, Office', max_length=100)),
                ('street_address', models.TextField()),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=13)),
                ('additional_notes', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_addresses', to='markets.market')),
                ('delivery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.deliveryzone')),
            ],
            options={
                'db_table': 'customer_addresses',
                'ordering': ['-is_default', 'label'],
            },
        ),
    ]
