# Generated by Django 5.2.8 on 2025-12-02 15:33

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFeeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Configuration name', max_length=100, unique=True)),
                ('calculation_method', models.CharField(choices=[('haversine', 'Haversine (Accurate)'), ('euclidean', 'Euclidean (Fast)'), ('manhattan', 'Manhattan (City blocks)')], default='haversine', help_text='Method for distance calculation', max_length=20)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Minimum delivery fee', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Fee per kilometer', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Order amount for free delivery', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_delivery_distance', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Maximum delivery distance in km', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('surcharge_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage surcharge for remote areas (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('delivery_time_estimate_per_km', models.IntegerField(default=3, help_text='Estimated minutes per km', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_delivery_time', models.IntegerField(default=30, help_text='Minimum delivery time in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_fee_configs',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='deliverytimeslot',
            options={'ordering': ['delivery_start_time']},
        ),
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ['market', 'priority', 'name']},
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='base_delivery_fee',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='is_manual_pricing',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='manual_delivery_fee',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='max_latitude',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='max_longitude',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='min_latitude',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='min_longitude',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='area',
            field=models.CharField(blank=True, help_text='Area/Neighborhood', max_length=255),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='distance_from_market',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from market in km', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='district',
            field=models.CharField(blank=True, help_text='District', max_length=255),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='estimated_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated delivery fee', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='estimated_delivery_time',
            field=models.IntegerField(blank=True, help_text='Estimated delivery time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Address has been verified'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='location_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic point for this address', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='region',
            field=models.CharField(blank=True, help_text='Region', max_length=255),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='ward',
            field=models.CharField(blank=True, help_text='Ward', max_length=255),
        ),
        migrations.AddField(
            model_name='deliverytimeslot',
            name='delivery_fee_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Fee multiplier for this time slot', max_digits=5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AddField(
            model_name='deliverytimeslot',
            name='max_orders',
            field=models.IntegerField(default=50, help_text='Maximum orders per slot', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Zone boundary polygon (draw on map)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='center_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Center point of the zone', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='distance_from_market',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from market in km', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='estimated_delivery_time',
            field=models.IntegerField(blank=True, help_text='Estimated delivery time in minutes', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed delivery price (for fixed price zones)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='priority',
            field=models.IntegerField(default=1, help_text='Priority (1=highest, 10=lowest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='surcharge_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Extra percentage charge (for surcharge zones)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='zone_type',
            field=models.CharField(choices=[('standard', 'Standard (Distance-based)'), ('fixed', 'Fixed Price'), ('free', 'Free Delivery'), ('surcharge', 'Surcharge Area'), ('unavailable', 'Delivery Unavailable')], default='standard', help_text='Type of delivery zone', max_length=20),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_addresses', to='location.deliveryzone'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='label',
            field=models.CharField(help_text='e.g., Home, Office, Shop', max_length=100),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='deliverytimeslot',
            name='cut_off_time',
            field=models.TimeField(help_text='Last order time for this slot'),
        ),
        migrations.AlterField(
            model_name='deliverytimeslot',
            name='delivery_end_time',
            field=models.TimeField(help_text='Delivery window end'),
        ),
        migrations.AlterField(
            model_name='deliverytimeslot',
            name='delivery_start_time',
            field=models.TimeField(help_text='Delivery window start'),
        ),
        migrations.AlterField(
            model_name='deliverytimeslot',
            name='name',
            field=models.CharField(help_text='e.g., Morning (8AM-12PM), Afternoon (12PM-4PM)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['customer', 'market', 'is_default'], name='customer_ad_custome_96472a_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['latitude', 'longitude'], name='customer_ad_latitud_e82c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['market', 'is_active'], name='delivery_zo_market__7176ee_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['zone_type', 'is_active'], name='delivery_zo_zone_ty_84a26d_idx'),
        ),
    ]
