# Generated by Django 5.2.8 on 2025-12-08 09:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_deliveryfeeconfig_alter_deliverytimeslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfeeconfig',
            name='distance_step_km',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.1'), help_text='Distance step in kilometers (e.g., 0.1 for 100m)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='deliveryfeeconfig',
            name='fee_per_step',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Fee for each distance step', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
