# Generated by Django 5.2.8 on 2026-01-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_deliveryfeeconfig_distance_step_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=12),
        ),
    ]
