# Generated by Django 5.2.8 on 2025-12-02 14:58

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+255xxxxxxxxx'. 12 digits required.", regex='^\\+255\\d{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('driver', 'Driver'), ('admin', 'Admin')], max_length=20)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_questions',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('names', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('can_manage_users', models.BooleanField(default=True)),
                ('can_manage_vendors', models.BooleanField(default=True)),
                ('can_manage_order', models.BooleanField(default=True)),
                ('can_manage_content', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('names', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('names', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_plate', models.CharField(max_length=20, unique=True)),
                ('license_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='license_image')),
                ('vehicle_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='vehicle_image')),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vendor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('names', models.CharField(max_length=255)),
                ('business_license', models.CharField(max_length=100, unique=True)),
                ('zanzibar_id', models.CharField(max_length=100, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('business_description', models.TextField(blank=True)),
                ('license_document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='license_document')),
                ('id_document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_document')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='UserSecurityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.securityquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_security_answers',
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='security_questions',
            field=models.ManyToManyField(through='accounts.UserSecurityAnswer', through_fields=('user', 'question'), to='accounts.securityquestion'),
        ),
    ]
