# Generated by Django 5.2.8 on 2025-12-08 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.market'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'market')},
        ),
    ]
