# Generated by Django 5.2.8 on 2025-12-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cart_customer_alter_cart_market_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Customer delivery latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location_name',
            field=models.CharField(blank=True, help_text='Name/label of delivery location (e.g., Home, Office)', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Customer delivery longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_street_address',
            field=models.TextField(blank=True, help_text='Full street address for delivery'),
        ),
    ]
