# Generated by Django 5.2.8 on 2026-01-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_ready_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_found',
            field=models.BooleanField(default=True, help_text='Checked by driver during market collection'),
        ),
    ]
