# Generated by Django 5.2.8 on 2025-12-02 14:58

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
                'db_table': 'global_settings',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnitType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_unit_name', models.CharField(help_text='e.g., gram, milliliter, meter', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'measurement_unit_types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addon_type', models.CharField(choices=[('preparation', 'Preparation'), ('service', 'Service'), ('packaging', 'Packaging'), ('delivery', 'Delivery')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_addons',
                'ordering': ['addon_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Default profit percentage for this category (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='category_image')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order in listings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
                ('typical_market_zones', models.ManyToManyField(blank=True, help_text='Market zones where this category is typically found', related_name='categories', to='markets.marketzone')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(help_text='e.g., kg, L, m, pcs', max_length=10)),
                ('conversion_factor', models.DecimalField(decimal_places=3, default=1.0, help_text='Conversion factor to base unit (e.g., 1000 for kg to grams)', max_digits=10)),
                ('is_base_unit', models.BooleanField(default=False, help_text='Is this the base unit for calculations?')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='products.measurementunittype')),
            ],
            options={
                'db_table': 'measurement_units',
                'ordering': ['unit_type', 'sort_order', 'name'],
                'unique_together': {('unit_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('main_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('search_keywords', models.TextField(blank=True, help_text='Comma-separated keywords for search and AI recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_units', models.ManyToManyField(help_text='Measurement units available for this product', related_name='products', to='products.measurementunit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('primary_unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.measurementunittype')),
                ('similar_products', models.ManyToManyField(blank=True, help_text='Manually define similar products for AI recommendations', to='products.producttemplate')),
            ],
            options={
                'db_table': 'product_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_image')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.producttemplate')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_profit_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Custom profit % (overrides category)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quality_grade', models.CharField(blank=True, choices=[('premium', 'Premium'), ('standard', 'Standard'), ('economy', 'Economy')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='markets.marketzone')),
                ('product_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.producttemplate')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.vendor')),
            ],
            options={
                'db_table': 'product_variants',
                'ordering': ['product_template__name', 'vendor__business_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAddonMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productaddon')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_addons', to='products.productvariant')),
            ],
            options={
                'db_table': 'product_addon_mappings',
            },
        ),
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_prices', to='products.productvariant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.measurementunit')),
            ],
            options={
                'db_table': 'unit_prices',
            },
        ),
        migrations.AddIndex(
            model_name='producttemplate',
            index=models.Index(fields=['name', 'category'], name='product_tem_name_da1ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='producttemplate',
            index=models.Index(fields=['is_active', 'is_verified'], name='product_tem_is_acti_48905a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product_template', 'vendor', 'market_zone')},
        ),
        migrations.AlterUniqueTogether(
            name='productaddonmapping',
            unique_together={('product_variant', 'addon')},
        ),
        migrations.AlterUniqueTogether(
            name='unitprice',
            unique_together={('product_variant', 'unit')},
        ),
    ]
